name: CI Workflow

# Triggers
on:
  push:
    branches: [ master ] # On push/commit to master (whenever `origin/master` receives a new commit)
  pull_request:
    types: [ opened ]
    branches: [ master ] # On commits to a PR into master
  workflow_dispatch: # Manual trigger (run via Actions -> CI Workflow (lefthand side) -> Run workflow)

# Jobs to run. Each job is a seperate container and may/may not have dependency jobs (like finishing building before testing)
jobs:
  # Compile the project. This job sets up the repository and subsequently builds the project.
  compile:
    name: Compile Project
    runs-on: macOS-latest
    strategy:
        matrix:
            destination: ['platform=iOS Simulator,name=iPhone 12 Pro'] # If you want to build for more devices, change this field to include whatever devices you want
    steps:
      - name: Checkout
        uses: actions/checkout@master
        # Set up SSH to fetch private HalloApp repositories
      - name: Set up ssh-agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.CI_PRIVATE_KEY }} # TODO: set up HalloApp bot account and issue new `CI_PRIVATE_KEY` (currently just using Matt's account)
      - name: Add known SSH hosts
        run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - name: Set git to use SSH
        run: git config --global url."git@github.com:".insteadOf "https://github.com/"
        
        # Load cached CocoaPods if the Podfile matches. Also creates end-of-script step to save the CocoaPods if the Podfile didn't match or wasn't cached
      - name: Cache Pods
        id: cache-pods
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
        # If the pods couldn't be loaded, then run `pod install` to fetch and build the `CocoaPods`
      - name: Install CocoaPods
        if: steps.cache-pods.outputs.cache-hit != 'true'
        run: pod install
        # Build the project for all devices
      - name: Build Project
        run: xcodebuild clean -workspace "Halloapp.xcworkspace" -scheme "Halloapp" -destination "${{matrix.destination}}"
      - name: Run Unit Tests
        run: xcodebuild test -workspace "Halloapp.xcworkspace" -scheme "Halloapp" -destination "${{matrix.destination}}" -only-testing "HalloAppTests"
      - name: Build Localizations
        run: xcodebuild -exportLocalizations -localizationPath . -project HalloApp.xcodeproj
        # Upload the localized files using the POEditor API
      - name: Upload Localizations
        run: curl -X POST https://api.poeditor.com/v2/projects/upload -F api_token=${{secrets.POEDITOR_API_KEY}} -F id="420915" -F updating="terms_translations" -F language="en" -F overwrite="1" -F fuzzy_trigger="1" -F file=@"en.xcloc/Localized Contents/en.xliff" -F tags="{\"obsolete\":\"removed-strings\"}"
