name: Master Unit Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Unit Tests
    runs-on: macOS-latest
    strategy:
        matrix:
            destination: ['platform=iOS Simulator,name=iPhone 12 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up ssh-agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.CI_PRIVATE_KEY }}
      - name: Add known SSH hosts
        run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      - name: Set git to use SSH
        run: git config --global url."git@github.com:".insteadOf "https://github.com/"
      - name: Install CocoaPods
        run: pod install
      - name: Build Project
        run: xcodebuild clean build-for-testing -workspace "Halloapp.xcworkspace" -scheme "Halloapp" -destination "${{matrix.destination}}"
      - name: Run Unit Tests
        run: xcodebuild test-without-building -workspace "Halloapp.xcworkspace" -scheme "Halloapp" -destination "${{matrix.destination}}" -only-testing "HalloAppTests"
